"""add models

Revision ID: 6f48cc24877a
Revises: 
Create Date: 2025-03-30 17:31:52.407898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f48cc24877a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('yandex_id', name=op.f('uq__users__yandex_id'))
    )
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__files__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__files'))
    )
    op.create_index(op.f('ix__files__filepath'), 'files', ['filepath'], unique=True)
    op.create_index(op.f('ix__files__id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__files__id'), table_name='files')
    op.drop_index(op.f('ix__files__filepath'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
